# first create a deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yourapp # rename to your app name
spec:
  selector:
    matchLabels:
      app: yourapp # rename to your app name
  replicas: 1
  template:
    metadata:
      labels:
        app: yourapp # rename to your app name
    spec:
      containers:
      - name: yourapp # rename to your app name
        image: dattarajrao/keras2kubernetes:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: yourapp # rename to your service name
  name: yourapp # rename to your service name
spec:
  ports:
  - port: 7001
    targetPort: 7001
  selector:
    app: yourapp # rename to your service name
  type: LoadBalancer
